name: commitlint

on:
  push:
    branches:
      - main
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  commitlint-check:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-commitlint:latest@sha256:158f13dcff181bab46cb6ebe13f719a9f0da6c5b0dd4dc4751947bd4f98f88c3

    steps:
      - uses: https://code.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: commitlint --last --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose