name: commitlint

on:
  push:
  pull_request:

jobs:
  forgejo:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-commitlint:latest@sha256:f202e07e9f96b1d4fe616736cc0ad56123ca7434d5ab0bbab44ab9da6ae15651

    steps:
      - uses: https://code.forgejo.org/actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: commitlint --last --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose