name: commitlint

on:
  push:
  pull_request:

jobs:
  forgejo:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-commitlint:latest@sha256:39d9057bfd855ea4c9782518779cf475bfb0f8f2ab54f881adc21e9ddd5497c8

    steps:
      - uses: https://code.forgejo.org/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: commitlint --last --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose