name: lint

on:
  push:
    branches:
      - main
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  lint-check:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:ea7c36b8403c7992f626a7d770c1f26982243f76aefaef22f7ea7849036d8fc0

    steps:
      - uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: check with ruff
        run: uv run ruff check src 
      - name: format with ruff
        run: uv run ruff format --check src 
      - name: check with pylint
        run: uv run pylint src || exit 0 