name: lint

on:
  push:
  pull_request:

jobs:
  forgejo:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:eb7f6936c0c2462eadc714564050bb64be3c3d1d4c2c3cc4481cc53c80dc006e

    steps:
      - uses: https://code.forgejo.org/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: check with ruff
        run: uv run ruff check src 
      - name: format with ruff
        run: uv run ruff format --check src 
      - name: check with pylint
        run: uv run pylint src || exit 0 