name: publish

on:
  push:
  pull_request:

jobs:
  forgejo:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:c43d992c307444b6675adeb9585c34edd8ea716ff717202cbff175d168262ebc

    steps:
      - uses: https://code.forgejo.org/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Build the project
        run: uv build
      - name: Publish release to pypi
        run: uv publish
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
      - name: Publish dev version to pypi
        run: uv publish
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}