---
name: PyInstaller Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: pyinstaller-bin
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git Tag Env
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Set up Python
        run: |
          apt-get update
          apt-get install -y python3 python3-apt python3-pip
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Build with pyinstaller
        run: ./scripts/build.py
      - name: Rename binary
        run: mv dist/pkg-exporter dist/pkg-exporter-${GIT_TAG}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/pkg-exporter-${GIT_TAG}